n1 = input('Digite algo: ')
print('O tipo primitivo de {} é {}'.format(n1,type(n1)))
print('Só contêm espaço?', n1.isspace())
print('É um número?', n1.isnumeric())
print('É alfabético?', n1.isalpha())
print('É alfanumérico?', n1.isalnum())
print('Está totalmente em maiúsculas?', n1.isupper())
print('Está totalmente em minúsculas?', n1.islower())
print('Está capitalizada?', n1.istitle())
